import {
  SiNextdotjs,
  SiTypescript,
  SiNodedotjs,
  SiMongodb,
  SiSocketdotio,
  SiAmazon,
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiPython,
  SiFlask,
  SiReact,
  SiTensorflow,
  SiFastapi,
  SiPostgresql,
  SiDocker,
  SiOpenai,
  SiTailwindcss,
  SiExpress,
  SiFirebase,
  SiThreedotjs,
  SiFramer,
  SiWebpack,
  SiOpencv,
  SiNumpy
} from 'react-icons/si'
import { IconType } from 'react-icons'

export const techIcons: Record<string, IconType> = {
  'Next.js': SiNextdotjs,
  'TypeScript': SiTypescript,
  'Node.js': SiNodedotjs,
  'MongoDB': SiMongodb,
  'WebSocket': SiSocketdotio,
  'AWS S3': SiAmazon,
  'HTML': SiHtml5,
  'CSS': SiCss3,
  'JavaScript': SiJavascript,
  'Python': SiPython,
  'Flask': SiFlask,
  'React': SiReact,
  'AI/ML': SiOpenai,
  'Machine Learning': SiOpenai,
  'Computer Vision': SiOpenai,
  'TensorFlow': SiTensorflow,
  'FastAPI': SiFastapi,
  'PostgreSQL': SiPostgresql,
  'Docker': SiDocker,
  'TailwindCSS': SiTailwindcss,
  'Express': SiExpress,
  'Firebase': SiFirebase,
  'Three.js': SiThreedotjs,
  'Framer Motion': SiFramer,
  'Webpack': SiWebpack,
  'OpenCV': SiOpencv,
  'NumPy': SiNumpy,
  'OpenAI': SiOpenai,
  'Performance APIs': SiJavascript
} 